name: CI/CD - Build and Deploy FastAPI Chatbot

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Error: Dockerfile not found!"
            exit 1
          fi
          echo "Dockerfile found."

      - name: Build and tag Docker image
        run: |
          # Build the Docker image and tag it for Artifact Registry
          echo "Building Docker image..."
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-agent/ai-chatbot:latest .

      - name: Authenticate Docker to Artifact Registry
        run: |
          echo "Authenticating Docker to Artifact Registry..."
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image to Artifact Registry..."
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-agent/ai-chatbot:latest

      - name: Deploy to Google Cloud Run
        run: |
          echo "Deploying to Google Cloud Run..."
          gcloud run deploy ai-chatbot \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ai-agent/ai-chatbot:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8000

      - name: Output Google Cloud Run URL
        run: |
          echo "Retrieving Google Cloud Run URL..."
          SERVICE_URL=$(gcloud run services describe ai-chatbot --platform managed --region us-central1 --format 'value(status.url)')
          echo "Google Cloud Run service URL: $SERVICE_URL"

