name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: 'agent-455009'  # 🔁 Replace with your GCP Project ID
  REGION: 'us-central1'
  SERVICE: 'ai-chat-service'  # 🔁 Your desired Cloud Run service name
  REPOSITORY_NAME: 'ai-chat-registry'  # 🔁 Artifact Registry name
  IMAGE_NAME: 'ai-chat'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_JSON }}'

      - name: 'Configure Docker for Artifact Registry'
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 'Build and Push Docker image'
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "Building image: $IMAGE_URI"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: 'Deploy to Cloud Run'
        id: deploy
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          gcloud run deploy ${{ env.SERVICE }} \
            --image "$IMAGE_URI" \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8501 \
            --set-env-vars "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }},OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},HOST=0.0.0.0,BACKEND_PORT=8080,FRONTEND_PORT=8501"

      - name: 'Show Deployed URL'
        run: |
          URL=$(gcloud run services describe ${{ env.SERVICE }} --region ${{ env.REGION }} --format='value(status.url)')
          echo "✅ App deployed at: $URL"
